ethereum:
  websocket_url: "wss://your-node-url"
  chain_id: 1

contracts:
  - name: "Vault"
    address: "0x..."
    start_block: 12345678
    abi_path: "vault.abi.json"
    events:
      - "Deposit"
      - "Withdraw"
      - "Transfer"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "vault_indexer"
  sslmode: "disable" 